name: Update Image and Deployment

on:
    pull_request:
        types: 
            - closed
        branches:
            - main

jobs:
    if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
      - run: |
          echo The PR was merged

    docker:
        needs: if_merged
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v3

            - 
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            -
                name: Build and push
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: true
                    tags: |
                        wanderar/frontend-client:latest
                        wanderar/frontend-client:${{ github.event.pull_request.title }}
                    platforms: linux/amd64

    update-deployment:
        needs: docker
        runs-on: ubuntu-latest
    
        steps:
            - name: Update docker-compose
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.IP_VPS_EPITECH_1 }}
                username: ${{ secrets.USER_VPS_EPITECH_1 }}
                key: ${{ secrets.KEY_VPS_EPITECH_1 }}
                port: ${{ secrets.PORT_VPS_EPITECH_1 }}
                script: |
                    cd frontend-client
                    if [ "$(docker ps -q -f name=frontend-client)" ]; then
                      docker compose down
                      docker compose pull
                    fi
                      docker compose up -d

            
